# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 进击的马斯特
subtitle: CODING MY LIFE
description: 前端 | 溜冰 | Mac
author: 马斯特
language: zh-CN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://pinkyjie.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/PinkyJie/pinkyjie.github.com.git
  branch: master
  name: PinkyJie
  email: pinkyjie.gn@gmail.com
  token: $GH_TOKEN

theme_config:
  scheme: Pisces

  menu:
    home: / || home
    about: /about/ || user
    tags: /tags/ || tags
    categories: /categories/ || th
    archives: /archives/ || archive

  social:
    GitHub: https://github.com/PinkyJie || github
    E-Mail: mailto:pinkyjie.gn@gmail.com || envelope
    Twitter: https://twitter.com/PinkyJie || twitter
    StackOverflow: http://stackoverflow.com/users/689948/pinkyjie || stack-overflow

  avatar:
    url: assets/images/avatar.jpg
    rounded: true
    opacity: 1
    rotated: false

  swiftype_key: 8k3UxSuRWYkrhVg55bC3

  google_site_verification: o7yQBnLIoWby8Y5vNMQywBiMtev-ilWjXt89RQpTvVw

  google_analytics: UA-45012422-1

  cnzz_siteid: 1253033676

  comments:
    active: gitalk

  math:
    mathjax:
      enable: true

  gitalk:
    enable: true
    github_id: PinkyJie
    repo: pinkyjie.github.com
    client_id: f9f9e61911dad3c54abd
    client_secret: 2de8c1e8bc1bf553827b0da3bf65ae6e7f5956b7
    admin_user: PinkyJie
    distraction_free_mode: true
    language:
